version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_api_foodservice
      MYSQL_ROOT_USE: root
      MYSQL_ROOT_PASSWORD: Password123
    ports:
      - "3306:3306"
    volumes: 
      - C:/docker_databases:/var/lib/mysql
    # command:
    #   - revoke all on db_api.* from 'root'@'%';
    #   - grant select, insert, delete, update on db_api.* to 'root'@'%';
    